######################################################################
# Automatically generated by qmake (3.0) Mon Mar 31 13:44:44 2014
######################################################################

TEMPLATE = app
QT += gui qml quick location positioning widgets

RESOURCES +=  main.qrc
SOURCES += src/main.cpp

target.path = /home/app/apps/$$TARGET
INSTALLS += target
